### ISSUE TITLE
Sync events ontwerp

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-sync#1]
De events in het sync component zijn de centrale 'API' van het systeem. Hierin of hieruit volgen de diverse informatiemodellen die ondersteund moeten worden: SensorPilot model, SensorThingAPI, SmartM2M, Open Urban Platform, diverse bestaande modellen van gemeenten (Amsterdam, Utrecht, Hilversum, ??) Deze worden in kadaster-labs/sensrnet-home#12 uitgewerkt. Dit issue zijn de events die in de Sync component gebruikt worden.

Event beschrijven de wijziging in de stand en weerspiegelen vaak de commands, de acties die aangeroepen worden op de APIs om wijzigingen aan te brengen (zie ook [mijn blog](https://levelup.gitconnected.com/paradigm-shift-from-single-model-to-commands-events-and-queries-ee68a97de9aa?source=friends_link&sk=df5dcf092d31eb2da5f6a95940cbd74f))

**Comment by kad-floriw** [comment]
De sync events zijn te vinden in https://github.com/kadaster-labs/sensrnet-sync/tree/master/src/sync/core/events
